spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.informix.jdbc.IfxDriver
    url: jdbc:informix-sqli://32.2.32.5:43001/invoicemgrdb:informixServer=server_dev;newcodeset=GBK,8859-1,819;
    username: weij
    password: piccpicc
    druid:
      #初始化大小、最小空闲、最大激活
      initial-size: 10
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

      validation-query: select count(*) from systables
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,log4j

      # 合并多个DruidDataSource的监控数据
#      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      remove-abandoned: true
      remove-abandoned-timeout-millis: 1800
  jpa:
    database: informix
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Informix10Dialect
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false